'''
File convert.py
@authors: Karla Vega & Heriberto Nieto, TACC Visualization Laboratory, http://www.tacc.utexas.edu/resources/visualization
'''

import sys
import os
import xml.etree.ElementTree as ET


# Usage convert.py info.txt movie.iso movie.mkv movie.mp4
filename1 = sys.argv[1] #txt filename generated by ffmpeg
filename2 = sys.argv[2] #original iso filename
filename3 = sys.argv[3] #mkv filename
filename5 = sys.argv[4] #mp4 filename
filename6 = sys.argv[5] #xml filename generated by mediaInfo
directory = os.path.dirname(filename2)
filename4 = directory+"/"+"convert.sh"

#variable declaration
cntVideo = 0
cntAudio = 0
cntSubtitle = 0
streamType = []
command = "ffmpeg -i "+filename2
aspectRatio = None

#parse xml for aspect ratio from VIDEO_TS.IFO
tree = ET.parse(filename6)
root = tree.getroot()

# traverse xml until File_extension == ifo 
index = 0
for child_element in tree.iterfind('File/track[@type="General"]/File_extension'):
    if child_element.text == "ifo":
        break
    else:
        index += 1
        
# get aspect ratio from <File> element located at index
aspectRatio = root[index].find('track[@type="Video"]/Display_aspect_ratio').text 
command = command + " -aspect " + aspectRatio

#open info file
with open(filename1) as f:
    for line in f:
        values = line.strip().split(' ')
        for text in values:
            if text=="Stream":
                streamType.append(values[2])
                
#start writing string to exectue

for type in streamType:
    if type=="Video:":
        cntVideo = cntVideo+1
    if type=="Audio:":
        cntAudio = cntAudio+1
    if type=="Subtitle:":
        cntSubtitle = cntSubtitle+1

for i in range(0, cntVideo):
    command = command + " -vcodec ffv1"

for i in range(0, cntAudio):
    command = command + " -acodec copy -ac 2"

for i in range(0, cntSubtitle):
    command = command + " -scodec copy"


#complete command
command = command + " -f matroska" +" "+ directory+"/"+filename3

if cntVideo>1:
    for i in range(1, cntVideo):
        command = command + " -newvideo"

elif cntAudio > 1:
    for i in range(1, cntAudio):
            command = command + ""

output = open(filename4, 'w')
output.write("!/bin/bash\n")
#write command to create mkv
output.write(command)
output.write("\n")
commandHB = "HandBrakeCLI -i "+filename2+" -o "+ directory+"/"+filename5
#wirte command to create mp4
output.write(commandHB)
output.close

#print error if file does not open
